wandb_version: 1

eps_start:
  desc: null
  value: 1
eps_end:
  desc: null
  value: 0.02
eps_decay:
  desc: null
  value: 100000
buffer_size:
  desc: null
  value: 15000
buffer_minimum:
  desc: null
  value: 10001
learning_rate:
  desc: null
  value: 5.0e-05
gamma:
  desc: null
  value: 0.99
n_iter_update_nn:
  desc: null
  value: 1000
multi_step:
  desc: null
  value: 2
double_dqn:
  desc: null
  value: false
dueling:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700046176.76828
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
