wandb_version: 1

env_name:
  desc: null
  value: ALE/Pong-ram-v5
state_size:
  desc: null
  value: 128
action_size:
  desc: null
  value: 6
seed:
  desc: null
  value: 0
n_episodes:
  desc: null
  value: 5000
eps_start:
  desc: null
  value: 1.0
eps_end:
  desc: null
  value: 0.01
eps_decay:
  desc: null
  value: 0.995
buffer_size:
  desc: null
  value: 100000.0
batch_size:
  desc: null
  value: 64
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.001
learning_rate:
  desc: null
  value: 0.0005
update_every:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699834079.964016
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
